FROM php:7.4

ARG PARALLEL_VERSION=v1.1.3

# Compile parallel
#RUN git clone -b "$PARALLEL_VERSION" --depth=1 https://github.com/krakjoe/parallel.git . && \
#    phpize && ./configure --with-php-config=/usr/bin/zts-php-config && \
#    make && make install && echo 'extension=parallel' >> /etc/php-zts.d/parallel.ini && \
#    rm -rf ./parallel
